### ISSUE TITLE
Compatibility Ionic 4

### ISSUE THREAD

**Issue by fcollombon** [hitmacreed/ng2-pdf-viewer-pinchZoom-Ionic-3#1]
Hello,

I try to use what you did with Ionic 4 but the Gesture import from ionic-angular is no longer available now... I looked for the equivalent but I found anything.

Thanks for your help,

François

**Comment by hitmacreed** [comment]
@fcollombon  Hi , thanks for letting me know,i will make a new update for ionic 4 soon thanks

**Comment by fcollombon** [comment]
Hi,

Have you made an update?

François

**Comment by hitmacreed** [comment]
@hitmacreed 
Hi,
I will create a new repositorie for that , and i will tag u 
cheers

**Comment by hitmacreed** [comment]
i have made other example using hammer js that use zoom directive but its more slow when zooming
check it here and let me know -> https://gist.github.com/hitmacreed/eed5d061c473c745702244b481aa5dfe
