### ISSUE TITLE
Scrool X and zoom bug

### ISSUE THREAD

**Issue by BriceFerna** [hitmacreed/ng2-pdf-viewer-pinchZoom-Ionic-3#3]
Hello!

Thank for your contribution, I've been seraching for a long time a way to pinch zoom with this ionic pdf reader.

I have 2 problems using your exemple :
- At the first display of my pdf, he's zoomed in even if I tuch nothing
- I can't scroll X even while putting overflow-x: scroll !important; with a high level of nesting

Do you have an idea? Thank you

**Comment by hitmacreed** [comment]
i maded in  a new way withi hammer js check this [gist](https://gist.github.com/hitmacreed/eed5d061c473c745702244b481aa5dfe)

**Comment by hitmacreed** [comment]
> Hello!
> 
> Thank for your contribution, I've been seraching for a long time a way to pinch zoom with this ionic pdf reader.
> 
> I have 2 problems using your exemple :
> 
> * At the first display of my pdf, he's zoomed in even if I tuch nothing
> * I can't scroll X even while putting overflow-x: scroll !important; with a high level of nesting
> 
> Do you have an idea? Thank you

i maded in  a new way with hammer js check this [gist] and let me know (https://gist.github.com/hitmacreed/eed5d061c473c745702244b481aa5dfe)
